### ISSUE TITLE
Add deprecation warning to OpenAI models: OpenAI has deprecated their logprobs API for user input

### ISSUE THREAD

**Issue by aalok-sathe** [aalok-sathe/surprisal#15]
OpenAI no longer provides log probs for the prompt, making it impossible to use as a probability over a string function. It does, however, continue to provide logprobs over its own completions.

E.g.:
![](https://i.imgur.com/cHhIW3m.png)

[Originally reported on twitter.](https://web.archive.org/web/20231001083359/https://twitter.com/xuanalogue/status/1707757449900437984)

**Comment by aalok-sathe** [comment]
Reopening, as [reported by OpenAI on X](https://twitter.com/OpenAIDevs/status/1735730662362189872) [openAI docs](https://platform.openai.com/docs/api-reference/chat/create#chat-create-logprobs), log probs seem to be available again, so it would be nice to re-build and test the (existing) support for this in our package. Thanks @jennhu!

**Comment by aalok-sathe** [comment]
@jennhu do you have a MWE for this with the new API? I just haven't used openai models in a while so if you have something that already works I wouldn't have to start over:)

**Comment by aalok-sathe** [comment]
if you have the bandwidth to PR even better but if not I'll take anything to start off of!

**Comment by jennhu** [comment]
After poking around some more with the chat models, I don't think we can get surprisals after all :(

The `logprobs` parameter lets us get the logprobs corresponding to the model's generated output, but without the `echo` parameter (as was previously supported by the legacy Completion models), we can't get the logprobs assigned to an arbitrary input string. It's possible I might be missing something, though!

**Comment by aalok-sathe** [comment]
I've already added a deprecation warning in README as of https://github.com/aalok-sathe/surprisal/commit/a926f9b; the API should continue working for older models supporting this endpoint (though I haven't tested it recently), but otherwise the broader issue about adding support is going to be a `wontfix`. Alternatives to OpenAI models include: MPT, Mistral, Llama, Falcon (not an exhaustive list or endorsement).
