### ISSUE TITLE
Dependency issues in Python 3.12

### ISSUE THREAD

**Issue by lpetley** [aalok-sathe/surprisal#22]
Hello,

I installed your Surprisal package with Python 3.12. Upon running a script that was essentially your test examples (the open AI variant), I received the message, "ModuleNotFoundError: No module named 'torch'." Looking further into the issue, I found that PyTorch has not been released yet for Python 3.12. Could you verify that your package works on Python 3.12, and if not, which version of Python do you recommend installing to use Surprisal?

**Comment by aalok-sathe** [comment]
Hm, thanks for reporting the issue with Python 3.12. I personally use 3.9-3.11 across a few projects, and haven't encountered this issue there. Maybe worth holding off on 3.12 until it is more widely supported?
